config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index", as: :about

  root to: "pages#index"

  #get "account", to: "billing_account#index"
  #get "account/pay", to: "billing_account#pay"
  #post "account/pay", to: "billing_account#update"

  get "register", to: "registrations#new"
  post "register", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
  get "logout", to: "sessions#destroy"

  get "user_profile", to: "user_profiles#edit"
  patch "user_profile", to: "user_profiles#update"
  post "user_profile/switch", to: "sessions#switch"

  # Password resets
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  #mount Pay::Engine, at: "/pay"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_error", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
# A way to ascribe attributes to the "current" user. Neat!
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  # any chars that are not a space or @ before @, one @, then the same
  # validation on right hand
  validates :email,
            presence: true,
            format: {
              with: /\A[^@\s]+@[^@\s]+\z/,
              message: "must be a valid email"
            }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user_logged_in!
    if Current.user.nil?
      redirect_to sign_in_path, alert: "You must be signed in to do that!"
    end
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  skip_before_action :set_current_user
  layout "static_page"

  def not_found
    render status: 404
  end

  def internal_error
    render status: 500
  end

  def unprocessable
    render status: 422
  end

  def unacceptable
    render status: 406
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    # Is this a real user?
    @user = User.find_by(email: params[:email])

    if @user.present?
      # Send email

      # Tell the PasswordMailer to wake up and send an email with (about) this user
      # Send the "reset" template
      # deliver_later means the browser response will be instant, and a background
      # job will send the email right away
      PasswordMailer.with(user: @user).reset.deliver_now
    end

    redirect_to root_path,
                notice:
                  "If an account with that email was found, we have sent a link to reset your password"
  end

  def edit
    @user = User.find_signed(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired. Please try again."
  end

  def update
    @user = User.find_signed(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path,
                  notice:
                    "Your password was reset successfully. Please sign in."
    else
      render :edit
    end
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save #if it's saved successfully in the db
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Your account has been created!"
    else
      render :new #new.html.erb
    end
  end

  def user_params
    # Only lets them set the attributes listed in .permit
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have been successfully logged out"
  end

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to user_profile_path, notice: "All changes saved."
    else
      render :edit
    end
  end

  private

  def password_params
    # This only allows us to change our password
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Literona</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    
    <div class="container">

    <%= render partial: "shared/flash" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
index

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>

   <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control"%>
  </div>

  <div class="mb-3">
    <%= form.submit "Reset my password", class: "btn btn-primary" %>
    </div>



<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password</h1>

<%= form_with url: password_reset_path do |form| %>

  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  
  <div class="mb-3">
    <%= form.submit "Get Password Reset Link", class: "btn btn-primary" %>
  </div>



<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Literona (prototype)", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Home", root_path, class: "nav-link navbar-expand-lg" %>
        
      </div>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <span class="navbar-text"><%= link_to Current.user.email, user_profile_path, class:'btn btn-small' %></span>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
        <% else %>

          <li class="nav-item">
            <%= link_to "Register", register_path, class:'btn btn-small' %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign in", sign_in_path, class:'btn btn-small'%>
          </li>
        
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/user_profiles/edit.html.erb
<h1>Your Profile</h1>

<%= form_with model: Current.user, url: user_profile_path do |form|  %>
  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end%>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", disabled: true, value: Current.user.email %>
  </div>
  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control"%>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
    </div>


<% end %>